"""Add user_id fk in budget_breakdown table

Revision ID: 3683376a8c95
Revises: 3089ab1672c8
Create Date: 2023-09-07 10:20:25.028426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3683376a8c95'
down_revision: Union[str, None] = '3089ab1672c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_breakdown', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'budget_breakdown', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'budget_breakdown', type_='foreignkey')
    op.drop_column('budget_breakdown', 'user_id')
    # ### end Alembic commands ###
