"""add last_updated column for table

Revision ID: 73c64f6cab00
Revises: c61bb6ad99c7
Create Date: 2023-10-13 14:44:54.538423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "73c64f6cab00"
down_revision: Union[str, None] = "c61bb6ad99c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "budget_breakdown", sa.Column("last_updated", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("budget_breakdown", "last_updated")
    # ### end Alembic commands ###
