"""make user columns nullable

Revision ID: c61bb6ad99c7
Revises: 3683376a8c95
Create Date: 2023-09-27 12:31:06.493410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c61bb6ad99c7"
down_revision: Union[str, None] = "3683376a8c95"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "given_name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "family_name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "nickname", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "picture", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "locale", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "updated_at", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "users", "email_verified", existing_type=sa.BOOLEAN(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "email_verified", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column("users", "updated_at", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "locale", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "picture", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "nickname", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "family_name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "given_name", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
